name: CI

on:
  push:
    branches:
      - dev
      - master
      - test-2764
  pull_request:
    branches:
      - dev
      - master
      - test-2764

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip packages
      uses: actions/cache@v2
      env:
        cache-name: cache-pypi-modules
      with:
        # pip cache files are stored in `~/.cache/pip` on Linux
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('requirements/requirements.txt', 'requirements/tests.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev coreutils
        sudo apt-get install -y gcc-4.8 g++-4.8
        export TERM=xterm-256color
        export CC="gcc-4.8"
        pip install -r requirements/tests.txt
        if [[ ${{ matrix.python-version }} == 3.9 ]]; then ./dev_setup.sh; fi
        # Skip mimic build for other versions because they should not differ
        if [[ ${{ matrix.python-version }} != 3.9 ]]; then ./dev_setup.sh -sm; fi
    - name: Codestyle
      run: |
        pycodestyle mycroft test
        flake8 mycroft test --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Tests
      run: |
        ./start-mycroft.sh unittest
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
